/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class ListarPersona extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form ListarPersona
     */

    public ListarPersona() {
        initComponents();
        llenarDatos();

    }

    public void llenarDatos() {
        modelo = (DefaultTableModel) tabla.getModel();
        int c = 0;
        int con = 0;
        int posicion;
        // Se obtiene la lista de controladorCliente 
        // Es un arreglo de un objeto
        while (con == 0) {
            try {
                String ruta = "C:\\Users\\Carlos\\OneDrive\\Documentos\\NetBeansProjects\\ArchivosBinarios\\src\\ec\\edu\\ups\\archivo\\datos.txt";
                RandomAccessFile archivo = new RandomAccessFile(ruta, "r");
                posicion = c * 152;
                archivo.seek(posicion);
                String nombre = archivo.readUTF().trim();
                archivo.seek(posicion + 52);
                String apellido = archivo.readUTF().trim();
                archivo.seek(posicion + 104);
                String cedula = archivo.readUTF();
                archivo.seek(posicion + 116);
                int edad = archivo.readInt();
                archivo.seek(posicion + 120);
                String fecha = archivo.readUTF();
                archivo.seek(posicion + 132);
                String celular = archivo.readUTF();
                archivo.seek(posicion + 144);
                double salario = archivo.readDouble();
                Object[] datos = {
                    cedula,
                    apellido,
                    nombre,
                    edad,
                    fecha,
                    celular,
                    salario,
                    c};
                modelo.addRow(datos);

                c++;
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ListarPersona.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException e) {
                con = 1;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombres", "Apellidos", "Edad", "Fecha Nacimiento", "Celular", "Sueldo", "Posicion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
